-- Esquema inicial. Ver docs/gestion-usuarios-roles.md §5.
-- Bootstrap manual hasta definir herramienta de migraciones (Flyway/Liquibase).

CREATE TABLE USUARIOS (
    ID              NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME        VARCHAR2(100)   NOT NULL UNIQUE,
    EMAIL           VARCHAR2(150)   NOT NULL UNIQUE,
    NOMBRE_COMPLETO VARCHAR2(200),
    ESTADO          VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIF     TIMESTAMP
);

CREATE TABLE ROLES (
    ID              NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100)   NOT NULL UNIQUE,
    DESCRIPCION     VARCHAR2(300),
    ESTADO          VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE USUARIO_ROL (
    USUARIO_ID       NUMBER    NOT NULL REFERENCES USUARIOS(ID),
    ROL_ID           NUMBER    NOT NULL REFERENCES ROLES(ID),
    FECHA_ASIGNACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (USUARIO_ID, ROL_ID)
);
